In [2]:
#Import Dependencies
import pandas as pd
from sqlalchemy import create_engine

In [7]:
clean_2016 = pd.read_csv('Resources/Cleaned_july_2016_data.csv')
clean_2019 = pd.read_csv('Resources/Cleaned_july_2019_data.csv')

clean_2016.head()

,Unnamed: 0,trip duration,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bike id,user type,birth year,gender,start_date,start_time,end_date,end_time
0,0,964,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,24706,Subscriber,1987.0,Male,2016-07-01,00:06:09,2016-07-01,00:22:14
1,1,472,3185,City Hall,40.717732,-74.043845,3192,Liberty Light Rail,40.711242,-74.055701,24504,Subscriber,1981.0,Female,2016-07-01,00:06:44,2016-07-01,00:14:37
2,2,565,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,24655,Subscriber,1990.0,Male,2016-07-01,00:10:39,2016-07-01,00:20:05
3,3,413,3195,Sip Ave,40.730743,-74.063784,3209,Brunswick St,40.724176,-74.050656,24446,Subscriber,1983.0,Male,2016-07-01,00:17:22,2016-07-01,00:24:15
4,4,436,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,24408,Subscriber,1988.0,Female,2016-07-01,00:37:31,2016-07-01,00:44:48